name: Docs check

on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: Gr1N/setup-poetry@v4
        with:
          poetry-version: 1.1.3
      - name: Build doc
        run: |
          poetry install
          poetry run make html
